spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: bank
    password: bankpw

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8081